version: '3.5'

services:
  padrao-site:
    build:
      context: '.'
    container_name: padrao-site
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "padrao-database"
      - "padrao-mail"
    networks:
      - app

  padrao-database:
    image: mysql:8
    tty: true
    container_name: padrao-database
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - DB_CONNECTION=mysql
      - DB_HOST=padrao-database
      - DB_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  padrao-mail:
    image: mailhog/mailhog:latest
    container_name: padrao-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=padrao
      - MT_PASSWD=padrao
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app
    
  padrao-redis:
    image: redis:latest
    container_name: padrao-redis
    ports:
      - 6379:6379
    networks:
      - app
networks:
  app:
    driver: bridge
